-- migrations/005_fix_users_schema.sql

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS favourite_animal TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT;
